version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "${APP_PORT}:80"
    environment:
      - TZ=Etc/UTC
